services:
  nav2-base:
    build:
      context: ./ros-humble-nav2-base
      dockerfile: Dockerfile
    image: ros-humble-nav2-base:latest

  nav2-gazebo:
    build:
      context: ./ros-humble-nav2-gazebo
      dockerfile: Dockerfile
    image: ros-humble-nav2-gazebo:latest
    depends_on:
      - nav2-base

  nav2-turtlebot3:
    build:
      context: ./ros-humble-nav2-turtlebot3
      dockerfile: Dockerfile
    image: ros-humble-nav2-turtlebot3:latest
    depends_on:
      - nav2-base
